(def O (tiledef
  (tile 12 8 1 1 0)
  (collision 0 0 1 1)))

(prefab
  OOOOOOOOOOOOOOOO
  OOOOOOOOOOOOOOOO
  OOOOOOOOOOOOOOOO
  OOOOOOOOOOOOOOOO
  OOOOOOOOOOOOOOOO
  OOOOOOOOOOOOOOOO
  OOOOOOOOOOOOOOOO
  OOOOOOOOOOOOOOOO
  OOOOOOOOOOOOOOOO
  OOOOOOOOOOOOOOOO
  OOOOOOOOOOOOOOOO
  OOOOOOOOOOOOOOOO
  OOOOOOOOOOOOOOOO
  OOOOOOOOOOOOOOOO
  OOOOOOOOOOOOOOOO
  OOOOOOOOOOOOOOOO
)
