(tiledef
  (id O)
  (tile 12 8 1 1 one_terrains_and_fences)
  (collision 0 0 1 1))

(prefab
  OOOOOOOOOOOOOOOO
  OOOOOOOOOOOOOOOO
  OOOOOOOOOOOOOOOO
  OOOOOOOOOOOOOOOO
  OOOOOOOOOOOOOOOO
  OOOOOOOOOOOOOOOO
  OOOOOOOOOOOOOOOO
  OOOOOOOOOOOOOOOO
  OOOOOOOOOOOOOOOO
  OOOOOOOOOOOOOOOO
  OOOOOOOOOOOOOOOO
  OOOOOOOOOOOOOOOO
  OOOOOOOOOOOOOOOO
  OOOOOOOOOOOOOOOO
  OOOOOOOOOOOOOOOO
  OOOOOOOOOOOOOOOO
)
